language: cpp
cache: ccache
matrix:
  include:
# osx conda package
  - name: Conda build, MacOS
    os: osx
    if: branch =~ ^test- OR tag IS present OR type IN(pull_request) OR type IN(cron)
    osx_image: xcode9.2
    env: PLUMED_CONDA=yes
install:
script:
  - CONDA_VERSION=none
  - export CONDA_LABEL=
# set CONDA_VERSION to TRAVIS_TAG, if available
  - if test -n "${TRAVIS_TAG}" ; then
       CONDA_VERSION="${TRAVIS_TAG//-/_}" ;
       CONDA_VERSION="${CONDA_VERSION#v}" ;
       CONDA_LABEL=tags ;
    fi
# set CONDA_VERSION to branch + date when on nightly build
  - if test "$TRAVIS_EVENT_TYPE" = cron ; then
       if test "$TRAVIS_BRANCH" = master ; then CONDA_VERSION=2.99.$(date +%y%m%d) ; fi ;
       if [[ "$TRAVIS_BRANCH" =~ ^v2.[0-9]+$ ]] ; then CONDA_VERSION=${TRAVIS_BRANCH#v}.$(date +%y%m%d) ; fi ;
       CONDA_LABEL=nightly ;
    fi
# build conda package
  - if test -n "$PLUMED_CONDA" ; then VERSION="$CONDA_VERSION" make -C conda ; fi
  - if test -n "$PLUMED_CONDA" && test -n "$CONDA_LABEL" ; then make -C conda upload ; fi
